// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace forfun.sandbox.uwns.util.pack.flat
{

using global::System;
using global::FlatBuffers;

public struct EnterWorldResponse : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static EnterWorldResponse GetRootAsEnterWorldResponse(ByteBuffer _bb) { return GetRootAsEnterWorldResponse(_bb, new EnterWorldResponse()); }
  public static EnterWorldResponse GetRootAsEnterWorldResponse(ByteBuffer _bb, EnterWorldResponse obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public EnterWorldResponse __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int Uid { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }

  public static Offset<EnterWorldResponse> CreateEnterWorldResponse(FlatBufferBuilder builder,
      int uid = 0) {
    builder.StartObject(1);
    EnterWorldResponse.AddUid(builder, uid);
    return EnterWorldResponse.EndEnterWorldResponse(builder);
  }

  public static void StartEnterWorldResponse(FlatBufferBuilder builder) { builder.StartObject(1); }
  public static void AddUid(FlatBufferBuilder builder, int uid) { builder.AddInt(0, uid, 0); }
  public static Offset<EnterWorldResponse> EndEnterWorldResponse(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<EnterWorldResponse>(o);
  }
};


}
