// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace forfun.sandbox.uwns.util.pack.flat
{

public enum Message : byte
{
 NONE = 0,
 EnterWorldResponse = 1,
 TargetPositionRequest = 2,
 SnapshotResponse = 3,
};


}
